import Foundation

/// ルーティンの円の中に表示できる SF Symbol の候補。編集画面で選ぶ。
enum RoutineIcon {
    /// 選択肢(SF Symbol 名)。iOS 17+ で存在するものだけを載せる。
    static let all: [String] = [
        "figure.walk",
        "figure.run",
        "figure.strengthtraining.traditional",
        "figure.yoga",
        "figure.mind.and.body",
        "figure.cooldown",
        "bicycle",
        "book",
        "book.closed",
        "pencil.and.outline",
        "text.book.closed",
        "brain.head.profile",
        "graduationcap",
        "laptopcomputer",
        "keyboard",
        "paintbrush.pointed",
        "guitars",
        "music.note",
        "camera",
        "leaf",
        "tree",
        "drop",
        "cup.and.saucer",
        "fork.knife",
        "carrot",
        "pills",
        "cross.case",
        "bed.double",
        "moon.stars",
        "sun.max",
        "alarm",
        "shower",
        "hands.and.sparkles",
        "heart",
        "dog",
        "cat",
        "pawprint",
        "sparkles",
        "flag",
        "target",
        "checklist",
        "list.bullet",
        "trophy",
        "star",
        "phone.down",
        "hourglass",
        "calendar",
        "dollarsign.circle",
    ]
}
